name: Node.js Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd ${{ matrix.dir }}
          npm ci
          npm install eslint@8.57.0 --save-dev
          npm install @eslint/object-schema @eslint/config-array --save-dev
          npm install rimraf@latest glob@latest --save-dev
          if [ "${{ matrix.dir }}" = "frontend" ]; then
            npm install swr
          fi
          if [ "${{ matrix.dir }}" = "backend" ]; then
            npm install --save-dev @types/pg @types/cors
          fi
      - name: Run ESLint
        run: cd ${{ matrix.dir }} && npm run lint